//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDTHING.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNDTHING.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CharacterList {
            get {
                object obj = ResourceManager.GetObject("CharacterList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Characters&gt;
        ///  &lt;Character&gt;
        ///    &lt;Name&gt;gjvygivhv&lt;/Name&gt;
        ///    &lt;ClassLevel&gt;vhkgukhv bnvn&lt;/ClassLevel&gt;
        ///    &lt;BackGround&gt;gygvgch&lt;/BackGround&gt;
        ///    &lt;PlayerName&gt;vygyugyg&lt;/PlayerName&gt;
        ///    &lt;Race&gt;jbh vhj&lt;/Race&gt;
        ///    &lt;Alignment&gt;guygcyg&lt;/Alignment&gt;
        ///    &lt;XP&gt;u8uhgv&lt;/XP&gt;
        ///    &lt;StrStat&gt;gygfcygy&lt;/StrStat&gt;
        ///    &lt;StrMod&gt;gvygv&lt;/StrMod&gt;
        ///    &lt;DexStat&gt;hbhv vh&lt;/DexStat&gt;
        ///    &lt;DexMod&gt;bhvuhv&lt;/DexMod&gt;
        ///    &lt;ConStat&gt;huhvh&lt;/ConStat&gt;
        ///    &lt;ConMod&gt; guhhv&lt;/ConMod&gt;
        ///    &lt;IntStat&gt;huihubh&lt;/IntStat&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Characters1 {
            get {
                return ResourceManager.GetString("Characters1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CharSheet {
            get {
                object obj = ResourceManager.GetObject("CharSheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainMenu1 {
            get {
                object obj = ResourceManager.GetObject("MainMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
